### ISSUE TITLE
Error when saving a new user

### ISSUE THREAD

**Issue by TimSullivan** [adelevie/parse_resource#77]
When I attempt to save a new user, I get an error:

```
TypeError in UsersController#create

class or module required for rescue clause

parse_resource (1.8.0) lib/parse_resource/base.rb:401:in `rescue in save'
parse_resource (1.8.0) lib/parse_resource/base.rb:390:in `save'
app/controllers/users_controller.rb:9:in `create'
```

The user class is pretty simple:

```
class User < ParseUser
  alias :email :username
  fields :email, :first_name, :last_name
end
```

I've tried to dig into things, and it appears to be that I'm getting 401 Unauthorized, however, when I do this in the console:

```
irb(main):005:0> u=User.new
=> #<User:0x007fd314251f40 @unsaved_attributes={}, @attributes={}, @error_instances=[]>
irb(main):006:0> u.email='tim@someemail.com'
=> "tim@someemail.com"
irb(main):007:0> u.username='tim@someemail.com'
=> "tim@someemail.com"
irb(main):008:0> u.password='password'
=> "password"

u.resource
=> #<RestClient::Resource:0x007fd31584d358 @url="https://api.parse.com/1/users", @block=nil, @options={:user=>"<AppID Removed>", :password=>"<API Key Removed>"}>
irb(main):006:0> u.create
RuntimeError: Parse error : Unknown Error unauthorized
```

The user and password fields seem correct. I've tried with both the REST API Key and the Master API Key, but in both cases, calling `create` brings up the error.

Using the standard parse-ruby-client gem works fine, so I know I've got the keys right.

**Comment by atmikev** [comment]
Having this same error with the User object in parse-rails-boilerplate project. Any updates?

**Comment by talkmithilesh** [comment]
I had same error, I fixed it by removing some unnecessary applicationId, and master key from global.json file
