### ISSUE TITLE
undefined method `constantize' for #<ActiveModel::Name:0x007fe29e8fc360>

### ISSUE THREAD

**Issue by foscomputerservices** [adelevie/parse_resource#87]
-- I'm using ruby 2.0.0p195 & rails 4.0.0 --

I'm receiving the above error for the line parse_user.rb:14

``` ruby
 user = model_name.constantize.new(JSON.parse(resp), false)
```

I see that this line has been changed post 1.8.0 to:

``` ruby
 user = model_name.*to_s*.constantize.new(JSON.parse(resp), false)
```

It seems that these changes have just not yet made it into production? Am I missing something?

**Comment by nickste** [comment]
The gem still hasn't been updated on RubyGems. To get around this you can include the code from the parse_resource github repo in your vendors folder. See here for more info: http://stackoverflow.com/questions/6800074/custom-ruby-gem-in-gemfile-on-heroku

**Comment by adelevie** [comment]
Anyone here want commit and rubygems push access?
